//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamCakes.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int ID_Pago { get; set; }
        public int ID_Pedido { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public int ID_Metodo { get; set; }
        public int ID_Estado { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
