//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamCakes.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION_PRODUCTO
    {
        public int ID_PromocionProducto { get; set; }
        public int ID_Promocion { get; set; }
        public int ID_Producto { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROMOCION PROMOCION { get; set; }
    }
}
