//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamCakes.Repositories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORACION
    {
        public int ID_Valoracion { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Producto { get; set; }
        public int Puntuacion { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
